services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    env_file:
      - .env
      - .env.local
    environment:
      - TOCKY_QUEUE_DB_PATH=/data/database.db
      - IA_CONFIG_FILE=/run/secrets/ia_config
    secrets:
      - ia_config
    ports:
      - "5000:5000"
    networks:
      - dbnet
    volumes:
      - queue_data:/data

networks:
  dbnet: {}

volumes:
  queue_data: {}

secrets:
  ia_config:
    file: ia_config.ini