services:
  app:
    build: ./app
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - dbnet
    volumes:
      - queue_data:/data

networks:
  dbnet: {}

volumes:
  queue_data: {}
