from typing import Literal
from lxml import etree
import re
from dataclasses import dataclass
import textwrap
import openai
import tiktoken

from tocky.extractor import AbstractExtractor, TocResponse
from tocky.ocr.printer import print_ocr
from tocky.utils import ShareableState, avg_ocr_conf
from tocky.utils.ia import get_djvu_by_leaf_nums, get_ia_metadata, get_page_scan, ocaid_to_djvu_url


class BadOcrOnToc(Exception):
  pass


@dataclass
class AiExtractorOptions:
  redo_ocr: bool = True
  ocr_engine: Literal['easyocr', 'tesseract', 'azure'] = 'easyocr'
  model: str = "gpt-4o-mini"
  system_prompt: str = textwrap.dedent("""
    You are a librarian extracting table of contents data in a structured format. The format you will need to output is as follows:

    ```
    * {label (optional)} | {title} | {page number}
    ```

    ### Important Instructions:
    - Fix any typos or bad characters generated by the OCR.
    - Change any text in ALL UPPERCASE to be in Normal Title Case.

    ### Examples:

    Input:
    ```
                                      PAGE
    PREFACE                             1x
    PART 1: THIS VVORLD                  1
      Chapter I.
      Of the Nature of Flatland
                                          3
      Chapter IT.
      Of the Cl'mate and Houses in
          Hlatland  . . . dsa. .a;;; ... 5
    PART 2: OTHER WORLDS
                                        42
    ```

    Output:
    ```
    * | Preface | ix
    * Part 1 | This World | 1
        ** Chapter I | Of the Nature of Flatland | 3
        ** Chapter II | Of the Climate and Houses in Flatland | 5
    * Part 2 | Other Worlds | 42
    ```


    Input:
    ```
          CONTENTS
    CHapter 1. ...... ... . . 1
    Ch^pter 2            .. @ 25
    Chaptr               .   38
    Chaptr  4                 48
    ```
    Output
    ```
    * | Chapter 1 | 1
    * | Chapter 2 | 25
    * | Chapter 3 | 38
    * | Chapter 4 | 48
    ```

    You can nest when necessary:

    Input:
    ```
    A. Technology
        Computers     ...       1
              Hard-drives        2
              Software           8
        II. Machinery           1[
      III. Hardware            3/
    B. Agriculture
    ```

    ```
    * A | Technology |
        ** I | Computers | 1
            *** | Hard-drives | 2
            *** | Software | 8
        ** II | Machinery | 11
        ** III | Hardware | 37
    * B | Agriculture |
    ```
  """)


class AiExtractor(AbstractExtractor[AiExtractorOptions]):
  P = AiExtractorOptions()
  S = ShareableState()

  def extract(self, ocaid: str, detector_result: list[int]) -> str:
    djvu_xml_to_fetch = set(detector_result) - set(self.S.ocr_cache.keys())
    if djvu_xml_to_fetch:
      djvu_url = ocaid_to_djvu_url(ocaid)
      start = min(djvu_xml_to_fetch)
      end = max(djvu_xml_to_fetch)
      for leaf_num, elem in get_djvu_by_leaf_nums(djvu_url, start, end):
        if leaf_num in djvu_xml_to_fetch:
          self.S.ocr_cache[leaf_num] = etree.tostring(elem, encoding='unicode')

    self.toc_raw_ocr = [
      print_ocr(
        self.redo_ocr(ocaid, leaf_num, self.S.ocr_cache[leaf_num])
        if self.P.redo_ocr
        else self.S.ocr_cache[leaf_num]
      )
      for leaf_num in detector_result
    ]

    if re.search(r'([A-Za-z]{25,}|\beee+\b)', '\n'.join(self.toc_raw_ocr), flags=re.MULTILINE):
      raise BadOcrOnToc("Bad OCR on TOC")

    self.toc_response = self.extract_structured_toc(self.toc_raw_ocr, get_ia_metadata(ocaid)['metadata']['title'])

    return self.toc_response.toc

  def redo_ocr(self, ocaid: str, leaf_num: int, djvu_xml: str) -> str:
    from tocky.ocr import ocr_djvu_page

    root = etree.fromstring(djvu_xml)
    if root.xpath('.//HIDDENTEXT/@x-re-ocrd') == ['true']:
      return djvu_xml

    new_ocr = ocr_djvu_page(get_page_scan(ocaid, leaf_num), engine=self.P.ocr_engine)
    new_ocr_el = etree.fromstring(new_ocr).find('.//HIDDENTEXT')
    if (avg_ocr_conf(new_ocr_el) or 100) > (avg_ocr_conf(root.find('.//HIDDENTEXT')) or 0):
      root.replace(root.find('.//HIDDENTEXT'), new_ocr_el)

    return etree.tostring(root, encoding='unicode')

  def extract_structured_toc(
    self,
    pages_ocr: list[str],
    book_title: str,
  ) -> TocResponse:
    structured_toc = ''
    prompt_tokens = 0
    completion_tokens = 0
    chunks = ['']
    for page_ocr in pages_ocr:
      extended_chunk = chunks[-1] + '\n' + page_ocr
      if len(tiktoken.encoding_for_model(self.P.model).encode(extended_chunk)) > 1_000:
        chunks.append(page_ocr)
      else:
        chunks[-1] += '\n' + page_ocr
    for chunk in chunks:
      toc_response = self.extract_structured_toc_chunk(chunk, book_title, prev_toc=structured_toc)
      structured_toc += '\n' + toc_response.toc.strip().strip('`').strip()
      prompt_tokens += toc_response.prompt_tokens
      completion_tokens += toc_response.completion_tokens
    
    return TocResponse(structured_toc, prompt_tokens, completion_tokens)

  def extract_structured_toc_chunk(
    self,
    ocr_text: str,
    book_title: str,
    prev_toc: str | None = None,
  ) -> TocResponse:
    if prev_toc:
      nline = '\n'
      message = textwrap.dedent(f"""
        The last table of contents was too long too fit in your context. Continue extracting the table of contents of "{book_title}".

        Here is the end of what you last output. Do not output this again, though.

        ```
        {nline.join(prev_toc.split(nline)[-10:])}
        ```

        And here is the rest of the OCR text:
        ```
        {ocr_text}
        ```
      """).strip()
    else:
      message = textwrap.dedent(f"""
        Extract the table of contents from this OCR text of "{book_title}":

        ```
        {ocr_text}
        ```
      """).strip()
    print('openai request', message[0:500] + '...')
    completion = openai.chat.completions.create(
      model=self.P.model,
      messages=[
        {"role": "system", "content": self.P.system_prompt},
        {"role": "user", "content": message},
      ],
      # max_tokens=1024,
      n=1,
      stop=None,
      temperature=0.5,
    )

    def clean_line(line: str) -> str:
      pipes = len(line.split('|')) - 1
      m = re.search(r'^ *\*+', line)
      if not m:
        return line
      stars = m.group()
      rest = line[m.span()[1]:]
      if pipes == 0:
        return f'{stars} | {rest.strip()} |'
      elif pipes == 1:
        return f'{stars} | {rest.strip()}'
      elif pipes == 2:
        return line
      elif pipes == 3:
        return line.replace('|', ' ', 1)
      else:
        # Not good
        return line

    assert completion.choices[0].message.content
    assert completion.usage

    toc = completion.choices[0].message.content.strip().strip('`')
    prompt_tokens = completion.usage.prompt_tokens
    completion_tokens = completion.usage.completion_tokens
    return TocResponse(
        '\n'.join(map(clean_line, toc.split('\n'))),
        prompt_tokens,
        completion_tokens)
