import re
from dataclasses import dataclass
import textwrap
import openai
import tiktoken

from tocky.utils import ShareableState


@dataclass
class TocResponse:
  toc: str
  prompt_tokens: int
  completion_tokens: int


@dataclass
class AiExtractorOptions:
  model: str = "gpt-4o-mini"
  system_prompt: str = textwrap.dedent("""
    You are a librarian extracting table of contents data in a structured format. The format you will need to output is as follows:

    ```
    * {label (optional)} | {title} | {page number}
    ```

    ### Important Instructions:
    - Fix any typos or bad characters generated by the OCR.
    - Change any text in ALL UPPERCASE to be in Normal Title Case.

    ### Examples:

    Input:
    ```
                                      PAGE
    PREFACE                             1x
    PART 1: THIS VVORLD                  1
      Chapter I.
      Of the Nature of Flatland
                                          3
      Chapter IT.
      Of the Cl'mate and Houses in
          Hlatland  . . . dsa. .a;;; ... 5
    PART 2: OTHER WORLDS
                                        42
    ```

    Output:
    ```
    * | Preface | ix
    * Part 1 | This World | 1
        ** Chapter I | Of the Nature of Flatland | 3
        ** Chapter II | Of the Climate and Houses in Flatland | 5
    * Part 2 | Other Worlds | 42
    ```


    Input:
    ```
          CONTENTS
    CHapter 1. ...... ... . . 1
    Ch^pter 2            .. @ 25
    Chaptr               .   38
    Chaptr  4                 48
    ```
    Output
    ```
    * | Chapter 1 | 1
    * | Chapter 2 | 25
    * | Chapter 3 | 38
    * | Chapter 4 | 48
    ```

    You can nest when necessary:

    Input:
    ```
    A. Technology
        Computers     ...       1
              Hard-drives        2
              Software           8
        II. Machinery           1[
      III. Hardware            3/
    B. Agriculture
    ```

    ```
    * A | Technology |
        ** I | Computers | 1
            *** | Hard-drives | 2
            *** | Software | 8
        ** II | Machinery | 11
        ** III | Hardware | 37
    * B | Agriculture |
    ```
  """)


class AiExtractor:
  P = AiExtractorOptions()
  S = ShareableState()

  def extract(self, ocaid: str, detector_result: list[int]) -> str:
    raise NotImplementedError()

  def extract_structured_toc(
    self,
    pages_ocr: list[str],
    book_title: str,
  ) -> TocResponse:
    structured_toc = ''
    prompt_tokens = 0
    completion_tokens = 0
    chunks = ['']
    for page_ocr in pages_ocr:
      extended_chunk = chunks[-1] + '\n' + page_ocr
      if len(tiktoken.encoding_for_model(self.P.model).encode(extended_chunk)) > 1_000:
        chunks.append(page_ocr)
      else:
        chunks[-1] += '\n' + page_ocr
    for chunk in chunks:
      toc_response = self.extract_structured_toc_chunk(chunk, book_title, prev_toc=structured_toc)
      structured_toc += '\n' + toc_response.toc.strip().strip('`').strip()
      prompt_tokens += toc_response.prompt_tokens
      completion_tokens += toc_response.completion_tokens
    
    return TocResponse(structured_toc, prompt_tokens, completion_tokens)

  def extract_structured_toc_chunk(
    self,
    ocr_text: str,
    book_title: str,
    prev_toc: str | None = None,
  ) -> TocResponse:
    if prev_toc:
      nline = '\n'
      message = textwrap.dedent(f"""
        The last table of contents was too long too fit in your context. Continue extracting the table of contents of "{book_title}".

        Here is the end of what you last output. Do not output this again, though.

        ```
        {nline.join(prev_toc.split(nline)[-10:])}
        ```

        And here is the rest of the OCR text:
        ```
        {ocr_text}
        ```
      """).strip()
    else:
      message = textwrap.dedent(f"""
        Extract the table of contents from this OCR text of "{book_title}":

        ```
        {ocr_text}
        ```
      """).strip()
    print('openai request', message[0:500] + '...')
    completion = openai.chat.completions.create(
      model=self.P.model,
      messages=[
        {"role": "system", "content": self.P.system_prompt},
        {"role": "user", "content": message},
      ],
      # max_tokens=1024,
      n=1,
      stop=None,
      temperature=0.5,
    )

    def clean_line(line: str) -> str:
      pipes = len(line.split('|')) - 1
      m = re.search(r'^ *\*+', line)
      if not m:
        return line
      stars = m.group()
      rest = line[m.span()[1]:]
      if pipes == 0:
        return f'{stars} | {rest.strip()} |'
      elif pipes == 1:
        return f'{stars} | {rest.strip()}'
      elif pipes == 2:
        return line
      elif pipes == 3:
        return line.replace('|', ' ', 1)
      else:
        # Not good
        return line

    assert completion.choices[0].message.content
    assert completion.usage

    toc = completion.choices[0].message.content.strip().strip('`')
    prompt_tokens = completion.usage.prompt_tokens
    completion_tokens = completion.usage.completion_tokens
    return TocResponse(
        '\n'.join(map(clean_line, toc.split('\n'))),
        prompt_tokens,
        completion_tokens)
